# fly -t local set-pipeline -p ontrack -c concourse/pipeline.yml -l concourse/parameters.yml -l concourse/secrets.yml

resources:
  - name: repo-code
    type: git
    source:
        uri: ((github-repo))
        branch: ((branch))
        ignore_paths: ["concourse/images/*"]
  - name: repo-images
    type: git
    source:
        uri: ((github-repo))
        branch: ((branch))
        paths: ["concourse/images/*"]
  - name: image-ontrack-ci
    type: docker-image
    source:
      repository: ((docker-hub-organization))/ontrack-ci-image
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      tag: ((docker-hub-tag))

jobs:
  - name: build-images
    plan:
    - get: repo-images
    - put: image-ontrack-ci
      params:
        build: images-code/concourse/images/ci
  - name: build
    plan:
      - get: image-ontrack-ci
      - get: repo-code
      - task: build
        image: image-ontrack-ci
        file: code/concourse/tasks/build.yml
